scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        labels:
          app: "prometheus"

  - job_name: "mlflow_model"
    static_configs:
      - targets: ["localhost:8000"]
        labels:
          app: "ml_model"
